package ru.levin.tmws.endpoint;

import ru.levin.tmws.api.endpoint.IServerEndpoint;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import java.net.MalformedURLException;
import java.net.URL;

/**
 * This class was generated by Apache CXF 3.2.7
 * 2019-07-18T17:33:08.575+03:00
 * Generated source version: 3.2.7
 *
 */
@WebServiceClient(name = "ServerEndpointService",
                  wsdlLocation = "http://localhost:8080/tm/ServerEndpoint?wsdl",
                  targetNamespace = "http://endpoint.tmws.levin.ru/")
public class ServerEndpointService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://endpoint.tmws.levin.ru/", "ServerEndpointService");
    public final static QName ServerEndpointPort = new QName("http://endpoint.tmws.levin.ru/", "ServerEndpointPort");
    static {
        URL url = null;
        try {
            url = new URL("http://localhost:8080/tm/ServerEndpoint?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(ServerEndpointService.class.getName())
                .log(java.util.logging.Level.INFO,
                     "Can not initialize the default wsdl from {0}", "http://localhost:8080/tm/ServerEndpoint?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public ServerEndpointService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public ServerEndpointService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ServerEndpointService() {
        super(WSDL_LOCATION, SERVICE);
    }

    public ServerEndpointService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public ServerEndpointService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public ServerEndpointService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }




    /**
     *
     * @return
     *     returns IServerEndpoint
     */
    @WebEndpoint(name = "ServerEndpointPort")
    public IServerEndpoint getServerEndpointPort() {
        return super.getPort(ServerEndpointPort, IServerEndpoint.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns IServerEndpoint
     */
    @WebEndpoint(name = "ServerEndpointPort")
    public IServerEndpoint getServerEndpointPort(WebServiceFeature... features) {
        return super.getPort(ServerEndpointPort, IServerEndpoint.class, features);
    }

}
