package ru.levin.tmws.api.endpoint;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.2.7
 * 2019-07-10T10:07:30.453+03:00
 * Generated source version: 3.2.7
 *
 */
@WebService(targetNamespace = "http://endpoint.api.tmws.levin.ru/", name = "IProjectEndpoint")
@XmlSeeAlso({ObjectFactory.class})
public interface IProjectEndpoint {

    @WebMethod
    @Action(input = "http://endpoint.api.tmws.levin.ru/IProjectEndpoint/updateProjectRequest", output = "http://endpoint.api.tmws.levin.ru/IProjectEndpoint/updateProjectResponse")
    @RequestWrapper(localName = "updateProject", targetNamespace = "http://endpoint.api.tmws.levin.ru/", className = "ru.levin.tmws.api.endpoint.UpdateProject")
    @ResponseWrapper(localName = "updateProjectResponse", targetNamespace = "http://endpoint.api.tmws.levin.ru/", className = "ru.levin.tmws.api.endpoint.UpdateProjectResponse")
    public void updateProject(
        @WebParam(name = "ticket", targetNamespace = "")
        ru.levin.tmws.api.endpoint.Session ticket,
        @WebParam(name = "project", targetNamespace = "")
        ru.levin.tmws.api.endpoint.Project project
    );

    @WebMethod
    @Action(input = "http://endpoint.api.tmws.levin.ru/IProjectEndpoint/getProjectTasksRequest", output = "http://endpoint.api.tmws.levin.ru/IProjectEndpoint/getProjectTasksResponse")
    @RequestWrapper(localName = "getProjectTasks", targetNamespace = "http://endpoint.api.tmws.levin.ru/", className = "ru.levin.tmws.api.endpoint.GetProjectTasks")
    @ResponseWrapper(localName = "getProjectTasksResponse", targetNamespace = "http://endpoint.api.tmws.levin.ru/", className = "ru.levin.tmws.api.endpoint.GetProjectTasksResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.util.List<ru.levin.tmws.api.endpoint.Task> getProjectTasks(
        @WebParam(name = "ticket", targetNamespace = "")
        ru.levin.tmws.api.endpoint.Session ticket,
        @WebParam(name = "project", targetNamespace = "")
        ru.levin.tmws.api.endpoint.Project project
    );

    @WebMethod
    @Action(input = "http://endpoint.api.tmws.levin.ru/IProjectEndpoint/removeProjectRequest", output = "http://endpoint.api.tmws.levin.ru/IProjectEndpoint/removeProjectResponse")
    @RequestWrapper(localName = "removeProject", targetNamespace = "http://endpoint.api.tmws.levin.ru/", className = "ru.levin.tmws.api.endpoint.RemoveProject")
    @ResponseWrapper(localName = "removeProjectResponse", targetNamespace = "http://endpoint.api.tmws.levin.ru/", className = "ru.levin.tmws.api.endpoint.RemoveProjectResponse")
    public void removeProject(
        @WebParam(name = "ticket", targetNamespace = "")
        ru.levin.tmws.api.endpoint.Session ticket,
        @WebParam(name = "project", targetNamespace = "")
        ru.levin.tmws.api.endpoint.Project project
    );

    @WebMethod
    @Action(input = "http://endpoint.api.tmws.levin.ru/IProjectEndpoint/removeProjectAllRequest", output = "http://endpoint.api.tmws.levin.ru/IProjectEndpoint/removeProjectAllResponse")
    @RequestWrapper(localName = "removeProjectAll", targetNamespace = "http://endpoint.api.tmws.levin.ru/", className = "ru.levin.tmws.api.endpoint.RemoveProjectAll")
    @ResponseWrapper(localName = "removeProjectAllResponse", targetNamespace = "http://endpoint.api.tmws.levin.ru/", className = "ru.levin.tmws.api.endpoint.RemoveProjectAllResponse")
    public void removeProjectAll(
        @WebParam(name = "ticket", targetNamespace = "")
        ru.levin.tmws.api.endpoint.Session ticket
    );

    @WebMethod
    @Action(input = "http://endpoint.api.tmws.levin.ru/IProjectEndpoint/createProjectRequest", output = "http://endpoint.api.tmws.levin.ru/IProjectEndpoint/createProjectResponse")
    @RequestWrapper(localName = "createProject", targetNamespace = "http://endpoint.api.tmws.levin.ru/", className = "ru.levin.tmws.api.endpoint.CreateProject")
    @ResponseWrapper(localName = "createProjectResponse", targetNamespace = "http://endpoint.api.tmws.levin.ru/", className = "ru.levin.tmws.api.endpoint.CreateProjectResponse")
    @WebResult(name = "return", targetNamespace = "")
    public ru.levin.tmws.api.endpoint.Project createProject(
        @WebParam(name = "ticket", targetNamespace = "")
        ru.levin.tmws.api.endpoint.Session ticket,
        @WebParam(name = "project", targetNamespace = "")
        ru.levin.tmws.api.endpoint.Project project
    );

    @WebMethod
    @Action(input = "http://endpoint.api.tmws.levin.ru/IProjectEndpoint/getProjectAllRequest", output = "http://endpoint.api.tmws.levin.ru/IProjectEndpoint/getProjectAllResponse")
    @RequestWrapper(localName = "getProjectAll", targetNamespace = "http://endpoint.api.tmws.levin.ru/", className = "ru.levin.tmws.api.endpoint.GetProjectAll")
    @ResponseWrapper(localName = "getProjectAllResponse", targetNamespace = "http://endpoint.api.tmws.levin.ru/", className = "ru.levin.tmws.api.endpoint.GetProjectAllResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.util.List<ru.levin.tmws.api.endpoint.Project> getProjectAll(
        @WebParam(name = "ticket", targetNamespace = "")
        ru.levin.tmws.api.endpoint.Session ticket
    );

    @WebMethod
    @Action(input = "http://endpoint.api.tmws.levin.ru/IProjectEndpoint/getProjectByIdRequest", output = "http://endpoint.api.tmws.levin.ru/IProjectEndpoint/getProjectByIdResponse")
    @RequestWrapper(localName = "getProjectById", targetNamespace = "http://endpoint.api.tmws.levin.ru/", className = "ru.levin.tmws.api.endpoint.GetProjectById")
    @ResponseWrapper(localName = "getProjectByIdResponse", targetNamespace = "http://endpoint.api.tmws.levin.ru/", className = "ru.levin.tmws.api.endpoint.GetProjectByIdResponse")
    @WebResult(name = "return", targetNamespace = "")
    public ru.levin.tmws.api.endpoint.Project getProjectById(
        @WebParam(name = "ticket", targetNamespace = "")
        ru.levin.tmws.api.endpoint.Session ticket,
        @WebParam(name = "projectId", targetNamespace = "")
        int projectId
    );

    @WebMethod
    @Action(input = "http://endpoint.api.tmws.levin.ru/IProjectEndpoint/getProjectByNameOrDescriptionRequest", output = "http://endpoint.api.tmws.levin.ru/IProjectEndpoint/getProjectByNameOrDescriptionResponse")
    @RequestWrapper(localName = "getProjectByNameOrDescription", targetNamespace = "http://endpoint.api.tmws.levin.ru/", className = "ru.levin.tmws.api.endpoint.GetProjectByNameOrDescription")
    @ResponseWrapper(localName = "getProjectByNameOrDescriptionResponse", targetNamespace = "http://endpoint.api.tmws.levin.ru/", className = "ru.levin.tmws.api.endpoint.GetProjectByNameOrDescriptionResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.util.List<ru.levin.tmws.api.endpoint.Project> getProjectByNameOrDescription(
        @WebParam(name = "ticket", targetNamespace = "")
        ru.levin.tmws.api.endpoint.Session ticket,
        @WebParam(name = "matcher", targetNamespace = "")
        java.lang.String matcher
    );
}
