package ru.levin.tmws.api.endpoint;

import javax.jws.WebMethod;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.2.7
 * 2019-07-18T17:36:29.356+03:00
 * Generated source version: 3.2.7
 *
 */
@WebService(targetNamespace = "http://endpoint.api.tmws.levin.ru/", name = "IServerEndpoint")
@XmlSeeAlso({ObjectFactory.class})
public interface IServerEndpoint {

    @WebMethod
    @Action(input = "http://endpoint.api.tmws.levin.ru/IServerEndpoint/getServerInfoRequest", output = "http://endpoint.api.tmws.levin.ru/IServerEndpoint/getServerInfoResponse")
    @RequestWrapper(localName = "getServerInfo", targetNamespace = "http://endpoint.api.tmws.levin.ru/", className = "ru.levin.tmws.api.endpoint.GetServerInfo")
    @ResponseWrapper(localName = "getServerInfoResponse", targetNamespace = "http://endpoint.api.tmws.levin.ru/", className = "ru.levin.tmws.api.endpoint.GetServerInfoResponse")
    @WebResult(name = "return", targetNamespace = "")
    public ru.levin.tmws.api.endpoint.ServerInfoDTO getServerInfo();
}
