package ru.levin.tmws.api.endpoint;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.2.7
 * 2019-07-10T10:35:10.422+03:00
 * Generated source version: 3.2.7
 *
 */
@WebService(targetNamespace = "http://endpoint.api.tmws.levin.ru/", name = "ISessionEndpoint")
@XmlSeeAlso({ObjectFactory.class})
public interface ISessionEndpoint {

    @WebMethod
    @Action(input = "http://endpoint.api.tmws.levin.ru/ISessionEndpoint/openSessionRequest", output = "http://endpoint.api.tmws.levin.ru/ISessionEndpoint/openSessionResponse")
    @RequestWrapper(localName = "openSession", targetNamespace = "http://endpoint.api.tmws.levin.ru/", className = "ru.levin.tmws.api.endpoint.OpenSession")
    @ResponseWrapper(localName = "openSessionResponse", targetNamespace = "http://endpoint.api.tmws.levin.ru/", className = "ru.levin.tmws.api.endpoint.OpenSessionResponse")
    @WebResult(name = "return", targetNamespace = "")
    public ru.levin.tmws.api.endpoint.Session openSession(
        @WebParam(name = "login", targetNamespace = "")
        java.lang.String login,
        @WebParam(name = "password", targetNamespace = "")
        java.lang.String password
    );

    @WebMethod
    @Action(input = "http://endpoint.api.tmws.levin.ru/ISessionEndpoint/closeSessionAllRequest", output = "http://endpoint.api.tmws.levin.ru/ISessionEndpoint/closeSessionAllResponse")
    @RequestWrapper(localName = "closeSessionAll", targetNamespace = "http://endpoint.api.tmws.levin.ru/", className = "ru.levin.tmws.api.endpoint.CloseSessionAll")
    @ResponseWrapper(localName = "closeSessionAllResponse", targetNamespace = "http://endpoint.api.tmws.levin.ru/", className = "ru.levin.tmws.api.endpoint.CloseSessionAllResponse")
    public void closeSessionAll(
        @WebParam(name = "ticket", targetNamespace = "")
        ru.levin.tmws.api.endpoint.Session ticket
    );

    @WebMethod
    @Action(input = "http://endpoint.api.tmws.levin.ru/ISessionEndpoint/closeSessionRequest", output = "http://endpoint.api.tmws.levin.ru/ISessionEndpoint/closeSessionResponse")
    @RequestWrapper(localName = "closeSession", targetNamespace = "http://endpoint.api.tmws.levin.ru/", className = "ru.levin.tmws.api.endpoint.CloseSession")
    @ResponseWrapper(localName = "closeSessionResponse", targetNamespace = "http://endpoint.api.tmws.levin.ru/", className = "ru.levin.tmws.api.endpoint.CloseSessionResponse")
    public void closeSession(
        @WebParam(name = "ticket", targetNamespace = "")
        ru.levin.tmws.api.endpoint.Session ticket
    );

    @WebMethod
    @Action(input = "http://endpoint.api.tmws.levin.ru/ISessionEndpoint/getSessionListRequest", output = "http://endpoint.api.tmws.levin.ru/ISessionEndpoint/getSessionListResponse")
    @RequestWrapper(localName = "getSessionList", targetNamespace = "http://endpoint.api.tmws.levin.ru/", className = "ru.levin.tmws.api.endpoint.GetSessionList")
    @ResponseWrapper(localName = "getSessionListResponse", targetNamespace = "http://endpoint.api.tmws.levin.ru/", className = "ru.levin.tmws.api.endpoint.GetSessionListResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.util.List<ru.levin.tmws.api.endpoint.Session> getSessionList(
        @WebParam(name = "ticket", targetNamespace = "")
        ru.levin.tmws.api.endpoint.Session ticket
    );

    @WebMethod
    @Action(input = "http://endpoint.api.tmws.levin.ru/ISessionEndpoint/getUserRequest", output = "http://endpoint.api.tmws.levin.ru/ISessionEndpoint/getUserResponse")
    @RequestWrapper(localName = "getUser", targetNamespace = "http://endpoint.api.tmws.levin.ru/", className = "ru.levin.tmws.api.endpoint.GetUser")
    @ResponseWrapper(localName = "getUserResponse", targetNamespace = "http://endpoint.api.tmws.levin.ru/", className = "ru.levin.tmws.api.endpoint.GetUserResponse")
    @WebResult(name = "return", targetNamespace = "")
    public ru.levin.tmws.api.endpoint.User getUser(
        @WebParam(name = "ticket", targetNamespace = "")
        ru.levin.tmws.api.endpoint.Session ticket
    );
}
