package ru.levin.tmws.api.endpoint;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.2.7
 * 2019-07-18T17:36:29.155+03:00
 * Generated source version: 3.2.7
 *
 */
@WebService(targetNamespace = "http://endpoint.api.tmws.levin.ru/", name = "ITaskEndpoint")
@XmlSeeAlso({ObjectFactory.class})
public interface ITaskEndpoint {

    @WebMethod
    @Action(input = "http://endpoint.api.tmws.levin.ru/ITaskEndpoint/addTaskToProjectRequest", output = "http://endpoint.api.tmws.levin.ru/ITaskEndpoint/addTaskToProjectResponse")
    @RequestWrapper(localName = "addTaskToProject", targetNamespace = "http://endpoint.api.tmws.levin.ru/", className = "ru.levin.tmws.api.endpoint.AddTaskToProject")
    @ResponseWrapper(localName = "addTaskToProjectResponse", targetNamespace = "http://endpoint.api.tmws.levin.ru/", className = "ru.levin.tmws.api.endpoint.AddTaskToProjectResponse")
    public void addTaskToProject(
        @WebParam(name = "ticket", targetNamespace = "")
        ru.levin.tmws.api.endpoint.SessionDTO ticket,
        @WebParam(name = "taskId", targetNamespace = "")
        java.lang.String taskId,
        @WebParam(name = "projectId", targetNamespace = "")
        java.lang.String projectId
    );

    @WebMethod
    @Action(input = "http://endpoint.api.tmws.levin.ru/ITaskEndpoint/removeTaskRequest", output = "http://endpoint.api.tmws.levin.ru/ITaskEndpoint/removeTaskResponse")
    @RequestWrapper(localName = "removeTask", targetNamespace = "http://endpoint.api.tmws.levin.ru/", className = "ru.levin.tmws.api.endpoint.RemoveTask")
    @ResponseWrapper(localName = "removeTaskResponse", targetNamespace = "http://endpoint.api.tmws.levin.ru/", className = "ru.levin.tmws.api.endpoint.RemoveTaskResponse")
    public void removeTask(
        @WebParam(name = "ticket", targetNamespace = "")
        ru.levin.tmws.api.endpoint.SessionDTO ticket,
        @WebParam(name = "task", targetNamespace = "")
        ru.levin.tmws.api.endpoint.TaskDTO task
    );

    @WebMethod
    @Action(input = "http://endpoint.api.tmws.levin.ru/ITaskEndpoint/updateTaskRequest", output = "http://endpoint.api.tmws.levin.ru/ITaskEndpoint/updateTaskResponse")
    @RequestWrapper(localName = "updateTask", targetNamespace = "http://endpoint.api.tmws.levin.ru/", className = "ru.levin.tmws.api.endpoint.UpdateTask")
    @ResponseWrapper(localName = "updateTaskResponse", targetNamespace = "http://endpoint.api.tmws.levin.ru/", className = "ru.levin.tmws.api.endpoint.UpdateTaskResponse")
    public void updateTask(
        @WebParam(name = "ticket", targetNamespace = "")
        ru.levin.tmws.api.endpoint.SessionDTO ticket,
        @WebParam(name = "task", targetNamespace = "")
        ru.levin.tmws.api.endpoint.TaskDTO task
    );

    @WebMethod
    @Action(input = "http://endpoint.api.tmws.levin.ru/ITaskEndpoint/getTaskByIdRequest", output = "http://endpoint.api.tmws.levin.ru/ITaskEndpoint/getTaskByIdResponse")
    @RequestWrapper(localName = "getTaskById", targetNamespace = "http://endpoint.api.tmws.levin.ru/", className = "ru.levin.tmws.api.endpoint.GetTaskById")
    @ResponseWrapper(localName = "getTaskByIdResponse", targetNamespace = "http://endpoint.api.tmws.levin.ru/", className = "ru.levin.tmws.api.endpoint.GetTaskByIdResponse")
    @WebResult(name = "return", targetNamespace = "")
    public ru.levin.tmws.api.endpoint.TaskDTO getTaskById(
        @WebParam(name = "ticket", targetNamespace = "")
        ru.levin.tmws.api.endpoint.SessionDTO ticket,
        @WebParam(name = "taskId", targetNamespace = "")
        int taskId
    );

    @WebMethod
    @Action(input = "http://endpoint.api.tmws.levin.ru/ITaskEndpoint/getTaskByNameOrDescriptionRequest", output = "http://endpoint.api.tmws.levin.ru/ITaskEndpoint/getTaskByNameOrDescriptionResponse")
    @RequestWrapper(localName = "getTaskByNameOrDescription", targetNamespace = "http://endpoint.api.tmws.levin.ru/", className = "ru.levin.tmws.api.endpoint.GetTaskByNameOrDescription")
    @ResponseWrapper(localName = "getTaskByNameOrDescriptionResponse", targetNamespace = "http://endpoint.api.tmws.levin.ru/", className = "ru.levin.tmws.api.endpoint.GetTaskByNameOrDescriptionResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.util.List<ru.levin.tmws.api.endpoint.TaskDTO> getTaskByNameOrDescription(
        @WebParam(name = "ticket", targetNamespace = "")
        ru.levin.tmws.api.endpoint.SessionDTO ticket,
        @WebParam(name = "matcher", targetNamespace = "")
        java.lang.String matcher
    );

    @WebMethod
    @Action(input = "http://endpoint.api.tmws.levin.ru/ITaskEndpoint/removeTaskAllRequest", output = "http://endpoint.api.tmws.levin.ru/ITaskEndpoint/removeTaskAllResponse")
    @RequestWrapper(localName = "removeTaskAll", targetNamespace = "http://endpoint.api.tmws.levin.ru/", className = "ru.levin.tmws.api.endpoint.RemoveTaskAll")
    @ResponseWrapper(localName = "removeTaskAllResponse", targetNamespace = "http://endpoint.api.tmws.levin.ru/", className = "ru.levin.tmws.api.endpoint.RemoveTaskAllResponse")
    public void removeTaskAll(
        @WebParam(name = "ticket", targetNamespace = "")
        ru.levin.tmws.api.endpoint.SessionDTO ticket
    );

    @WebMethod
    @Action(input = "http://endpoint.api.tmws.levin.ru/ITaskEndpoint/getTaskAllRequest", output = "http://endpoint.api.tmws.levin.ru/ITaskEndpoint/getTaskAllResponse")
    @RequestWrapper(localName = "getTaskAll", targetNamespace = "http://endpoint.api.tmws.levin.ru/", className = "ru.levin.tmws.api.endpoint.GetTaskAll")
    @ResponseWrapper(localName = "getTaskAllResponse", targetNamespace = "http://endpoint.api.tmws.levin.ru/", className = "ru.levin.tmws.api.endpoint.GetTaskAllResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.util.List<ru.levin.tmws.api.endpoint.TaskDTO> getTaskAll(
        @WebParam(name = "ticket", targetNamespace = "")
        ru.levin.tmws.api.endpoint.SessionDTO ticket
    );

    @WebMethod
    @Action(input = "http://endpoint.api.tmws.levin.ru/ITaskEndpoint/createTaskRequest", output = "http://endpoint.api.tmws.levin.ru/ITaskEndpoint/createTaskResponse")
    @RequestWrapper(localName = "createTask", targetNamespace = "http://endpoint.api.tmws.levin.ru/", className = "ru.levin.tmws.api.endpoint.CreateTask")
    @ResponseWrapper(localName = "createTaskResponse", targetNamespace = "http://endpoint.api.tmws.levin.ru/", className = "ru.levin.tmws.api.endpoint.CreateTaskResponse")
    @WebResult(name = "return", targetNamespace = "")
    public ru.levin.tmws.api.endpoint.TaskDTO createTask(
        @WebParam(name = "ticket", targetNamespace = "")
        ru.levin.tmws.api.endpoint.SessionDTO ticket,
        @WebParam(name = "task", targetNamespace = "")
        ru.levin.tmws.api.endpoint.TaskDTO task
    );
}
